spring:
  aop:
    auto: true
  sql:
    init:
      platform: h2
      mode: always  # Ensure SQL files like schema.sql/data.sql are executed
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true

logging:
  level:
    root: info
    com.gagan: debug
    org.hibernate.SQL: debug

app:
  email:
    enabled: false

