name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven (skip tests here)
      run: mvn clean package -DskipTests

    - name: Run Tests
      run: mvn test
      env:
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
        RAZOR_PUBLIC_KEY: ${{ secrets.RAZOR_PUBLIC_KEY }}
        RAZOR_PRIVATE_KEY: ${{ secrets.RAZOR_PRIVATE_KEY }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        FACEBOOK_TOKEN_VALIDATION_URL: ${{ secrets.FACEBOOK_TOKEN_VALIDATION_URL }}
        SERVER_PORT: 8080
